"""Milestone 4.8 -- generates the exact literal prompt_text for each of
the 12 real agents' canonical v1 prompt_registry row, from the actual
_LEGACY_* constants still defined in the three agent base classes. Run
once to produce the SQL seeded live to dev and committed into
supabase/seed.sql -- guarantees byte-identical wording to what Milestone
4.4/4.6/4.7 actually shipped (Mac's "preserve prompt wording" instruction),
never hand-transcribed.

Usage: python scripts/generate_prompt_registry_seed.py
"""
from __future__ import annotations

import json

from app.agents.base_agent import _LEGACY_SYSTEM_PROMPT_TEMPLATE
from app.agents.sequential_base import (
    _LEGACY_AGENT_OUTPUT_INSTRUCTIONS,
    _LEGACY_PROBABILITY_OUTPUT_INSTRUCTIONS,
    _LEGACY_SEQUENTIAL_SYSTEM_PROMPT_TEMPLATE,
)
from app.agents.consensus_review_base import (
    _LEGACY_ELITE_HARD_RULE,
    _LEGACY_ELITE_SCHEMA,
    _LEGACY_META_HARD_RULE,
    _LEGACY_META_SCHEMA,
    _LEGACY_SYSTEM_PROMPT_TEMPLATE as _LEGACY_REVIEW_SYSTEM_PROMPT_TEMPLATE,
)

CONTEXT_DATA_AGENTS = [
    "injury_intelligence_agent",
    "weather_agent",
    "travel_fatigue_agent",
    "rest_days_agent",
    "vegas_line_agent",
    "closing_line_movement_agent",
]

AGENT_OUTPUT_SEQUENTIAL_AGENTS = ["expected_value_agent", "risk_manager_agent", "bankroll_coach_agent"]
PROBABILITY_OUTPUT_SEQUENTIAL_AGENTS = ["probability_modeling_agent"]


def build_prompts() -> dict[str, str]:
    prompts: dict[str, str] = {}

    for name in CONTEXT_DATA_AGENTS:
        prompts[name] = _LEGACY_SYSTEM_PROMPT_TEMPLATE.format(agent_name=name)

    for name in AGENT_OUTPUT_SEQUENTIAL_AGENTS:
        prompts[name] = _LEGACY_SEQUENTIAL_SYSTEM_PROMPT_TEMPLATE.format(
            agent_name=name, output_instructions=_LEGACY_AGENT_OUTPUT_INSTRUCTIONS
        )

    for name in PROBABILITY_OUTPUT_SEQUENTIAL_AGENTS:
        prompts[name] = _LEGACY_SEQUENTIAL_SYSTEM_PROMPT_TEMPLATE.format(
            agent_name=name, output_instructions=_LEGACY_PROBABILITY_OUTPUT_INSTRUCTIONS
        )

    prompts["meta_agent"] = _LEGACY_REVIEW_SYSTEM_PROMPT_TEMPLATE.format(
        agent_name="meta_agent", hard_rule=_LEGACY_META_HARD_RULE, schema=_LEGACY_META_SCHEMA
    )
    prompts["consensus_reconciliation_agent"] = _LEGACY_REVIEW_SYSTEM_PROMPT_TEMPLATE.format(
        agent_name="consensus_reconciliation_agent", hard_rule=_LEGACY_ELITE_HARD_RULE, schema=_LEGACY_ELITE_SCHEMA
    )

    return prompts


def sql_literal(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def main() -> None:
    prompts = build_prompts()
    assert len(prompts) == 12, f"expected 12 agent prompts, got {len(prompts)}"

    print("-- generated by scripts/generate_prompt_registry_seed.py -- do not hand-edit")
    print("insert into prompt_registry (prompt_name, version, prompt_text, status, owner) values")
    lines = []
    for name in sorted(prompts):
        lines.append(f"  ({sql_literal(name)}, 1, {sql_literal(prompts[name])}, 'active', 'milestone-4.8-seed')")
    print(",\n".join(lines) + ";")

    # Also dump as JSON for the live-apply step, to avoid re-deriving SQL escaping twice.
    with open("/tmp/prompt_registry_seed.json", "w") as f:
        json.dump(prompts, f)


if __name__ == "__main__":
    main()
